version: "3"

services: 
  rails: 
    build: rails_image
    volumes:
      - ./:/home/app
      - ./bundle_cache:/usr/local/bundle
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 1234
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  db: {}