default: &default
  adapter: postgresql
  encoding: unicode
  username: rails
  password: rails
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: rails
  password: rails
  database: recipe_app_development

test:
  <<: *default
  username: rails
  password: rails
  database: recipe_app_test

production:
  <<: *default
  database: recipe_app_production
  username: rails
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
